chfast/intx

CMakeLists.txt

CMake option to enable or disable building tests in IntX. On by default.

Add INTX_TESTING OPTION

---

include/intx/int128.hpp
include/intx/intx.hpp

This allows easier integration with full intx package.

int128: Define uint128 as the uint<128> specialization

---

include/intx/int128.hpp
include/intx/intx.hpp
lib/intx/div.cpp
lib/intx/div.hpp
test/benchmarks/bench_div.cpp
test/unittests/test_div.cpp

This makes 256-bit division ~40% faster and 512-bit division ~10% slower.
```
Benchmark                                   Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------------
udiv<uint256, uint32_t, udivrem>         -0.4528         -0.4528         56945         31162         56945         31162
udiv<uint256, uint64_t, udivrem>         -0.3995         -0.3995         55146         33118         55145         33117
udiv<uint256, uint128, udivrem>          -0.4197         -0.4198         58186         33763         58186         33762
udiv<uint256, uint256, udivrem>          -0.0868         -0.0869         37118         33894         37117 …
```

Division improvements

---

CHANGELOG.md
include/intx/int128.hpp
include/intx/intx.hpp
test/unittests/test_intx.cpp
test/unittests/test_intx_api.cpp

Closes #105.
This reworks and extends mostly the `intx::be` API for converting to/from bytes in big-endian order.
The usage is shown in https://github.com/ethereum/evmone/pull/131/files.
After prototyping the usage of new API, I propose further changes:
- Rename `uint<N>` to `load<uint<N>>`. In the end it is more consistent so see `be::load<uint256>(...)` instead of `be::uint<256>` and would allow to support other types like `be::load<int256>`.
- Rename `uint_unsafe()` to `unsafe_load()` or `unsafe::load()`. The later would allow hiding the "unsafe" mark with `using namespace intx::be::unsafe`.
- Rename `store_unsafe()` to `unsafe_store()` or `unsafe::store()`.

Rework and extend endian-specific conversion API

---

CHANGELOG.md
circle.yml
include/intx/int128.hpp
include/intx/intx.hpp
test/benchmarks/CMakeLists.txt
test/benchmarks/bench_builtins.cpp
test/unittests/CMakeLists.txt
test/unittests/test_builtins.cpp
test/unittests/test_int128.cpp
test/unittests/test_intx_api.cpp

Constexpr clz()

---

include/intx/int128.hpp
include/intx/intx.hpp
test/benchmarks/benchmarks.cpp
test/experimental/add.cpp

This rewrites the `add_with_carry()` for `uint128` to a bit more efficient form (easier to consume by compilers).
Also subtraction is implemented in the analogous way to additions, instead of reusing addition.
GCC9:
```
Comparing test/intx-bench-master to test/intx-bench
Benchmark                           Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------
binary_op256<add>                +0.0007         +0.0007          7186          7191          7186          7191
binary_op256<inline_add>         -0.1695         -0.1695          2317          1924          2317          1924
binary_op256<sub>                -0.1624         -0.1625          8707 …
```

Optimize add and sub

---

lib/intx/div.cpp

This improves GCC10 build:
```
div<uint256, udivrem>/64_mean                   +0.0148         +0.0148            25            25            25            25
div<uint256, udivrem>/128_mean                  -0.0688         -0.0688            32            29            32            29
div<uint256, udivrem>/192_mean                  -0.0184         -0.0184            36            35            36            35
div<uint256, udivrem>/256_mean                  -0.0061         -0.0061            32            32            32            32
div<uint512, udivrem>/64_mean                   -0.0880         -0.0880            43            39            43            39
div<uint512, udivrem>/128_mean                  -0.1567         -0.1567            58            49            58            49 …
```

div: Optimize udivrem_byN()

---

lib/intx/div.cpp

Mark add-back step and division overflow case as unlikely.
Clang 10:
```
div<uint256, udivrem>/64_mean                   -0.0029         -0.0029            32            32            32            32
div<uint256, udivrem>/128_mean                  -0.0129         -0.0129            32            32            32            32
div<uint256, udivrem>/192_mean                  -0.0480         -0.0480            36            34            36            34
div<uint256, udivrem>/256_mean                  -0.0595         -0.0595            33            31            33            31
div<uint512, udivrem>/64_mean                   +0.0039         +0.0039            57            57            57            57
div<uint512, udivrem>/128_mean                  +0.0176         +0.0176            56 …
```

Mark unlikely parts of division

---

include/intx/intx.hpp

This replaces `2 ^ E` with `1 << E` as suggested in https://github.com/ethereum/evmone/pull/233.
Three versions have been tried
1. ```cpp
result << exponent 
```
2. ```cpp
if (exponent < N)
{
auto exp_bytes = as_bytes(exponent);
uint8_t bit_to_set = exp_bytes[0];
exp_bytes[0] = 0;
exp_bytes[bit_to_set >> 3] = uint8_t(uint8_t(1) << (bit_to_set & 7));
return exponent;
}
3. ```cpp
auto result = uint<N>{0};
if (exponent < N)
{
auto bit_to_set = static_cast<uint64_t>(exponent);
as_words(result)[bit_to_set / 64] = uint64_t{1} << (bit_to_set % 64);
}
return result;
```
Comparing master with v1:
```
Benchmark                                    Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------- …

Optimize exponentiation of base 2

---

include/intx/intx.hpp

```
exponentiation/64_mean                    -0.0977         -0.0976           693           625           693           625
exponentiation/128_mean                   -0.1046         -0.1046          1447          1296          1447          1296
exponentiation/192_mean                   -0.1089         -0.1089          2205          1965          2205          1965
exponentiation/256_mean                   -0.1095         -0.1095          2966          2641          2966          2641
```

Add sqr(), use it for exp()

---

circle.yml
cmake/CableCompilerSettings.cmake
include/intx/int128.hpp
test/unittests/test_int128.cpp
test/unittests/test_intx.cpp
test/unittests/test_utils.hpp

Add support for building without exceptions

---

include/intx/int128.hpp

Use guaranteed lossless conversion with {}.

int128: Cleanup conversion to __int128

---

include/intx/int128.hpp

The Clang compiler loves this pattern and will generate optimal subtraction procedure. And the code is also simpler although not symmetric to addition any more.
```
binop<uint256, uint256, sub>                                        -0.4896         -0.4896             3             2             3             2
binop<uint256, uint256, inline_sub>                                 -0.3636         -0.3635             2             1             2             1
binop<uint512, uint512, sub>                                        -0.4397         -0.4397             7             4             7             4
binop<uint512, uint512, inline_sub>                                 -0.5787         -0.5787             6             3             6             3
```
Before:
```
0000000000412390 …
```

Change subtraction overflow condition in sub_with_carry()

---

include/intx/intx.hpp

This turned out to be the fastest procedure if benchmarked correctly. Only the "public_mul" for `uint256` should be affected.
Skylake, Clang11
```
binop<uint256, uint256, mul_>_mean                           -0.0003         -0.0003            13            12            13            12
binop<uint256, uint256, mul_loop_>_mean                      +0.0032         +0.0032            30            30            30            30
binop<uint256, uint256, mul_loop_opt_>_mean                  -0.0006         -0.0006            11            11            11            11
binop<uint256, uint256, public_mul>_mean                     -0.0474         -0.0474            12            12            12            12
binop<uint256, uint256, gmp::mul>_mean                       +0.0361         +0.0361 …
```

Always use mul_loop_opt() for multiplication (operator*)

---

include/intx/int128.hpp
include/intx/intx.hpp
test/benchmarks/bench_int128.cpp
test/unittests/test_int128.cpp

Pulled out of https://github.com/chfast/intx/pull/180 with a test fixed in a boring way.

Cleanup umul()

---

include/intx/int128.hpp
include/intx/intx.hpp
test/unittests/test_intx.cpp

This simplifies reduction from any intx::uint to the shift amount param
because we can just use the lowest word for this.

Change shift amount param from unsigned to uint64_t 

---

circle.yml

The clang coverage after converting to lcov format is not very precise
and causes some false-positive uncovered empty lines for example.

ci: Do not upload clang coverage to codecov

---

include/intx/intx.hpp

For `uint256` this is slower than `x * x`. We mostly care about this case only because squaring is used in `exp()`.
I also tried word-based "optimized" `sqr()`
```cpp
inline constexpr uint<256> sqr(const uint<256>& x) noexcept
{
uint<256> r;
auto p = umul(x[0], x[0]);
r[1] = p[1];
r[0] = p[0];
p = umul(x[1], x[1]);
r[3] = p[1];
r[2] = p[0];
uint<256> s;
for (size_t j = 0; j < 2; j++)
{
uint64_t k = 0;
for (size_t i = 1; i < (4 - 2 * j - 1); i++)
{
const auto t = umul(x[i], x[j]) + s[i + j] + k;
s[i + j] = t[0];
k = t[1];
}
s[4 - 1] += x[4 - j - 1] * x[j] + k;
}
s = s << 1;
return r + s;
}
```
Also slower (although should have smaller cost. I believe the shift `<< 1` kills the performance.

Remove sqr()

---

include/intx/intx.hpp
test/unittests/test_intx.cpp
test/unittests/test_utils.hpp

Allow constructing uint type for any number of 64-bit words.
This also enables basic tests for uint192 and uint384 types.

Enable uint<> of any multiple of 64

---

include/intx/intx.hpp
test/unittests/test_intx.cpp

Moved from evmone EVM implementation. Can be later used to implement
signed type adapter.

Add "signed less than" comparison

---

include/intx/intx.hpp
test/unittests/test_intx.cpp

Restore previous shift implementation of shift for uint256 which uses
two 128-bit halves. This one is much faster.

Restore previous shift implementation for uint256

---

include/intx/intx.hpp

```
Comparing o/lt-old to o/lt-new
Benchmark                                        Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------
compare<lt_public>/64_mean                    -0.1253         -0.1254             3             3             3             3
compare<lt_public>/128_mean                   -0.1269         -0.1269             3             3             3             3
compare<lt_public>/192_mean                   -0.1253         -0.1253             3             3             3             3
compare<lt_public>/256_mean                   -0.1262         -0.1262             3             3             3             3
```

Restore previous less-than implementation for uint256

---

include/intx/intx.hpp
test/unittests/test_builtins.cpp
test/unittests/test_intx.cpp

Add implementation of bswap uint8_t, uint16_t and uint32_t and delete
other overloading. Also add tests for be::unsafe::load to make sure
they work correctly now.

Add support for bswap of small types

---

circle.yml
cmake/toolchains/powerpc64.cmake
include/intx/intx.hpp
test/unittests/test_builtins.cpp
test/unittests/test_intx.cpp

Add to_little_endian()/to_big_endian() helpers converting internal representations to/from requested byte order.
Also fix store()/load() functions to work correctly on big-endian architectures.

Add big-endian support

---

include/intx/intx.hpp

In the multiplication loop add two uint64_t values with addc() instead of extending to uint128.

Optimize multiplication loop

---

include/intx/intx.hpp

Inline subc() in submul() and use borrow flag idiom
which is recognizable by GCC.

Optimize submul part of udivrem

---

include/intx/intx.hpp
test/benchmarks/benchmarks.cpp

The new implementation is similar to what was there: we select which half to compare and do 128-bit less-than. For small values this is equivalent to do subtraction + borrow check, for big values though we get 25% boost.

Optimize less-than

---

include/intx/intx.hpp

The bug in GCC prevents some optimizations if a local struct variable (like `uint256`) is `const`. This PR removes some `const`s that affects the optimization. See bug report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106786.
```
mod<addmod_public>/64                                         -0.1555         -0.1555            38            32            38            32
mod<addmod_public>/128                                        -0.0741         -0.0741            35            32            35            32
mod<addmod_public>/192                                        -0.1834         -0.1834            45            36            45            36
mod<addmod_public>/256                                        -0.1706         -0.1706            40            33            40            33 …
```

"Optimize" GCC by removing `const`

---

include/intx/intx.hpp
test/benchmarks/benchmarks.cpp
test/fuzzer/fuzz_intx.cpp
test/unittests/test_intx.cpp

This is critical for EVM `MSTORE` and `MLOAD`. GCC was not properly optimizing these because of the https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107837 bug.
```
load_store_be<uint128>_mean                  +0.0115         +0.0114             2             2             2             2
load_store_be<uint256>_mean                  -0.8506         -0.8506            23             3            23             3
load_store_be<uint512>_mean                  -0.4334         -0.4335            40            23            40            23
```

Optimize BE load and store of uint256

---

circle.yml
include/intx/intx.hpp

This fixes a build failure. [`_umul128` is x64 only](https://learn.microsoft.com/en-us/cpp/intrinsics/umul128?view=msvc-170), so [using `_M_X64`](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170) for checking that.

Enable 32-bit Windows build in CircleCI

---

.clang-tidy
CMakeLists.txt
appveyor.yml
circle.yml
cmake/CableCompilerSettings.cmake
include/intx/intx.hpp
test/CMakeLists.txt
test/unittests/test_builtins.cpp
test/unittests/test_int128.cpp
test/unittests/test_intx_api.cpp

Update compiler settings. Disable some warnings in intx.hpp source, not in CMake so it is easier to use a copy of intx.hpp in other projects.
Fixes #285.

cmake: Update compiler settings

---

CHANGELOG.md
include/intx/intx.hpp

The C++ compiler from Xcode 14.3.1 miscompiles __builtin_subcll on arm64 / Apple M1 architectures.
This change disables usage of the builtin in this compiler version.
Replaces #293.
Fixes #292.

Fix buggy __builtin_subcll in Xcode 14.3.1 on arm64

---

circle.yml

This exclude filter was used to omit random tests
but there are not random tests any more.

ci: Drop tests exclude filter

---

include/intx/intx.hpp

This decouples loop end expression from the iterator decrement. Previously, the `it--` produced invalid iterator to `u[-1]` in the last iteration. It might have not been a big deal for execution because the loop terminated and the iterator was unused, but this was theoretical undefined behavior and constexpr context didn't like it either.

Avoid producing invalid iterators in division loops

---

include/intx/intx.hpp

In case the division numerator is 0 its computed number of words `m` is also 0. Then avoid accessing `un[m-1]`.
This is not a critical bug because in the worst case we increased the `m` by 1 but results were computed correctly.

Fix division of numerator 0

---

include/intx/intx.hpp
test/unittests/test_intx_api.cpp

Fill the gap in the type aliases and literas in the range 128-512. Also place the literal operators in the intx::literals namespace to allow using the literals without `using namespace intx`.

Add type aliases and literals up to uint512

---

include/intx/intx.hpp

Use `if constexpr` instead of function overloading to specialize implementations of some operators for uint256.

Rework specialization for uint256

---

test/CMakeLists.txt

Enable `-Zc:preprocessor` and `-permissive-` compiler flags when testing MSVC builds.

cmake: Force MSVC standards conformance mode

---

include/intx/intx.hpp
test/unittests/test_intx_api.cpp

Extend `uint` types with support for three-way comparison operator (`<=>`).
Closes #295.

Add support for c++20 spaceship operator <=>

---

include/intx/intx.hpp

Fixes this warning from clang:
```
In file included from D:/src/test.cpp:6:
D:/src/intx/include/intx/intx.hpp:1622:1: warning: identifier '_u128' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
1622 | DEFINE_ALIAS_AND_LITERAL(128);
| ^
D:/src/intx/include/intx/intx.hpp:1617:34: note: expanded from macro 'DEFINE_ALIAS_AND_LITERAL'
1617 |     consteval uint##N operator"" _u##N(const char* s) \
|                                  ^
<scratch space>:168:1: note: expanded from here
168 | _u128
```

Remove whitespace in literal operator declarations

---

include/intx/intx.hpp

In C++23 the `float_denorm_style`, `has_denorm` and `has_denorm_loss` of `std::numeric_limits` have been deprecated.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2614r2.pdf

Don't specify deprecated float_denorm_style

---

include/intx/intx.hpp

Add asserts/assumption statements to udivrem that the number of words in the argument out of normalization are not negative. This helps clang static analysis to avoid false positives.

Assume word counts out of div normalization are not negative

---

test/benchmarks/bench_div.cpp
test/experimental/CMakeLists.txt
test/experimental/div.hpp
test/unittests/test_div.cpp

Merge two copies of `reciprocal_native()` into single inline function used by both benchmarks and unit tests.

test: Extract reciprocal_native()
